name: IBM Cloud Deploy

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * *'

defaults:
  run:
    shell: bash

env:
  IBM_ACCOUNT: ${{ secrets.IBM_ACCOUNT }}
  RESOURSE_ID: ${{ secrets.RESOURSE_ID }}
  IBM_APP_NAME: ${{ secrets.IBM_APP_NAME }}
  IBM_MEMORY: ${{ secrets.IBM_MEMORY }}
  
  
  
  VLESS_EN: ${{ secrets.VLESS_EN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        run: |
          ./deploy.sh
          
